### ISSUE TITLE
user authentication not properly configured

### ISSUE THREAD

**Issue by emito-k** [COS301-SE-2023/xPOSE#28]
The frontend, needs better way of accessing the uid of the currently logged in user

**Comment by Ibango7** [comment]
I had angular local variables but it does not seem to be the the safest way, furthermore due to  sync properties it does not get latest result everytime. 
So for now I put the function in the  shared component auth.services.ts. Whenever you'd want the uid you can get it from them by importing auth.services to the component you want it in and gethold of the  specific function. At least there will be no need to keep on wrting it again and again.

**Comment by emito-k** [comment]
The latest code I've been using the getCurrentUserId() function, no longer use that?

**Comment by Ibango7** [comment]
Yes it does use it getCurrentUserId(). Essentially I just got that function and put it in the **shared component. Auth.service.ts** so that whenever uid is needed we can just get it from by importing  Auth.service.ts
